// Code generated by sqlc. DO NOT EDIT manually — regenerate with `make sqlc`
// For M1: hand-written stub. Run `make sqlc` once sqlc is installed.
package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

type Queries struct {
	pool *pgxpool.Pool
}

func New(pool *pgxpool.Pool) *Queries {
	return &Queries{pool: pool}
}

// GetHealth executes a minimal query to confirm DB connectivity.
func (q *Queries) GetHealth(ctx context.Context) (int32, error) {
	var ok int32
	err := q.pool.QueryRow(ctx, "SELECT 1").Scan(&ok)
	return ok, err
}
